Add Unit-Test Framework
Args-Engine/Args-Engine pull request #129
Opened 2020-09-27 10:15 UTC by Algo-ryth-mix

Adresses #68 (not a fix however)

Finally adds a unit-test framework to the repository https://github.com/onqtam/doctest

check `unit_test/test_filesystem` for how to use this framework

2020-09-28 11:53 UTC, Developer-The-Great approved these changes

2020-09-29 10:44 UTC, GlynLeine requested changes

2020-09-29 10:44 UTC, GlynLeine commented on args/application/context/detail/KHR/khrplatform.h
> +   /*-------------------------------------------------------------------------
indenting of this entire file is now wrong

2020-09-29 10:44 UTC, GlynLeine commented on args/application/context/detail/glad/glad.c
> +	Specification: gl
this file as well

2020-09-29 10:44 UTC, GlynLeine commented on args/application/context/detail/glad/glad.h
> -    APIs: gl=4.6
and this one

2020-09-29 10:49 UTC, GlynLeine approved these changes

2020-09-29 11:10 UTC, merged