image in core and window system overhoal
Args-Engine/Args-Engine pull request #153
Opened 2020-10-08 22:22 UTC by GlynLeine

2020-10-08 23:15 UTC, GlynLeine commented
Had to fix a missing null check for an audio segment in order to run it. I also cleaned up the OpenAL context info logging.

2020-10-08 23:16 UTC, GlynLeine commented
![image](https://user-images.githubusercontent.com/50330170/95522688-0ca4ba80-09cd-11eb-99ba-2452fd5a9b8c.png)

2020-10-09 13:50 UTC, Algo-ryth-mix approved these changes

2020-10-09 13:56 UTC, Developer-The-Great requested changes

2020-10-09 13:56 UTC, Developer-The-Great commented on args/core/data/image.cpp
> +    }
this is quite a huge function, some comments might be necessary

2020-10-09 13:57 UTC, Developer-The-Great approved these changes

2020-10-09 14:01 UTC, merged