Collision Resolution Unit Tests and bug fixes
Args-Engine/Args-Engine pull request #159
Opened 2020-10-19 15:28 UTC by Developer-The-Great

- Created Collision Resolution unit tests for later
- Created some debugging helpers for physics
- Fixed a bug where adding a rigidbodies would cause entities to visually dissapear

2020-10-26 08:41 UTC, Algo-ryth-mix requested changes

2020-10-26 08:41 UTC, Algo-ryth-mix commented on legion/engine/physics/colliders/convexcollider.cpp
> +#include <physics/data/identifier.h>
why with the .h again

2020-10-26 08:41 UTC, Algo-ryth-mix commented on legion/engine/physics/data/identifier.h
> +}
this file should be .hpp instead of .h

2020-10-26 08:41 UTC, Algo-ryth-mix commented on legion/engine/physics/physics_contact.h
> +			//where Ib is the 3x3 matrix inertia tensor of the rigidbodyB,
I trust you on this one chief

2020-10-26 15:32 UTC, Algo-ryth-mix approved these changes

2020-10-27 08:20 UTC, GlynLeine requested changes

2020-10-27 08:20 UTC, GlynLeine commented on legion/engine/physics/physicsconstants.h
>  }
this file should be .hpp

2020-10-27 08:20 UTC, GlynLeine commented on legion/engine/physics/physics_contact.h
>  		math::mat4 refTransform;
this file should be .hpp instead of .h

2020-10-27 08:38 UTC, GlynLeine approved these changes

2020-10-27 08:54 UTC, merged