Feature/glTF loading
Args-Engine/Args-Engine pull request #212
Opened 2020-11-25 13:02 UTC by Jelled1st

adds glb file loading (binary gltf)

2020-11-25 16:00 UTC, Developer-The-Great commented on legion/engine/core/data/importers/mesh_importers.cpp
> +    }
I think some refactoring would be helpfull and or commenting would be helpfull

2020-11-25 16:01 UTC, Developer-The-Great commented on legion/engine/core/data/importers/mesh_importers.cpp
> +    }
also might need a refactor

2020-11-25 16:03 UTC, Developer-The-Great requested changes
needs refactoring in some places

2020-11-30 10:02 UTC, Developer-The-Great approved these changes

2020-11-30 10:14 UTC, GlynLeine requested changes

2020-11-30 10:14 UTC, GlynLeine commented on deps/include/tinygltf/stb_image.h
> +   #include ...
are we including this header twice now?

2020-11-30 10:14 UTC, GlynLeine commented on legion/engine/core/data/importers/mesh_importers.cpp
> +        }*/
cleanup commented out code?

2020-11-30 10:14 UTC, GlynLeine commented on legion/engine/core/data/importers/mesh_importers.cpp
> +                log::debug("Color component type: float");
might wanna remove the debug logs or turn them into trace logs, keep the warnings tho

2020-11-30 10:14 UTC, GlynLeine commented on legion/engine/core/data/importers/mesh_importers.cpp
> +            log::debug("Color accessor type: Vec4");
same story, either remove debug log or turn them into trace logs, this is not interesting to a gameplay programmer.

2020-11-30 10:14 UTC, GlynLeine commented on legion/engine/core/data/importers/mesh_importers.cpp
> +            log::debug("Loading submesh: {}", m.name);
same story

2020-11-30 10:14 UTC, GlynLeine commented on legion/engine/core/data/importers/mesh_importers.cpp
> +                        log::warn("\n\n\n\nMore data to be found in .gbl. Data can be accesed through: {}\n\n\n", attrib.first);
why all the `\n`???

2020-11-30 10:14 UTC, GlynLeine commented on legion/engine/core/data/importers/mesh_importers.cpp
> +            log::warn("Warning: {}", warn);
error and warning already do the whole "error:" thing

2020-11-30 10:14 UTC, GlynLeine commented on legion/engine/core/data/importers/mesh_importers.cpp
> +            log::debug("Loading submesh: {}", m.name);
same story as before

2020-11-30 10:14 UTC, GlynLeine commented on legion/engine/core/data/importers/mesh_importers.cpp
> +                        log::debug("Vertices count: {}", meshData.vertices.size());
same story as before

2020-11-30 10:14 UTC, GlynLeine commented on legion/engine/core/data/importers/mesh_importers.cpp
> +                        log::warn("\n\n\n\nMore data to be found in .gbl. Data can be accesed through: {}\n\n\n", attrib.first);
`\n\n\n\n`???

2020-11-30 10:44 UTC, GlynLeine commented on legion/engine/core/data/importers/mesh_importers.cpp
> +     * \param data - std::Vector<T> where the buffer is going to be copied into. The vector will be resized to vector.size()+(tinygltf data size)
We use `@param` not `\param`

2020-11-30 10:46 UTC, GlynLeine approved these changes

2020-11-30 11:21 UTC, merged