Feature/lap 17 renderer rework
Args-Engine/Args-Engine pull request #227
Opened 2020-12-02 21:49 UTC by GlynLeine

2020-12-10 16:07 UTC, Algo-ryth-mix approved these changes
overall more comments required, some lines need manual formating.
Try to keep pr shorter

2020-12-10 16:07 UTC, Algo-ryth-mix commented on legion/engine/core/common/managed_resource.hpp
> +}
there is not a single comment here

2020-12-10 16:07 UTC, Algo-ryth-mix commented on legion/engine/core/ecs/entity_handle.cpp
> +        (void)ent;
should probably be [[mabye_unused]] instead ?

2020-12-10 16:07 UTC, Algo-ryth-mix commented on legion/engine/rendering/data/buffer.hpp
> +}
needs a lot of comments

2020-12-10 16:07 UTC, Algo-ryth-mix commented on legion/engine/rendering/data/framebuffer.hpp
> +}
also comments here please

2020-12-10 16:07 UTC, Algo-ryth-mix commented on legion/engine/rendering/data/renderbuffer.hpp
> +    };
no comments, some manual formating required: lines exceed what github is able to show in one line

2020-12-11 08:44 UTC, tuhri444 approved these changes

2020-12-11 08:59 UTC, kukash approved these changes

2020-12-11 11:14 UTC, Algo-ryth-mix requested changes
see previous msgs

2020-12-14 08:17 UTC, Algo-ryth-mix approved these changes

2020-12-14 09:05 UTC, merged