fix logging for release
Args-Engine/Args-Engine pull request #266
Opened 2020-12-20 23:03 UTC by GlynLeine

2020-12-21 21:16 UTC, Ragingram2 approved these changes

2020-12-21 21:22 UTC, Algo-ryth-mix requested changes

2020-12-21 21:22 UTC, Algo-ryth-mix commented on legion/engine/core/logging/logging.cpp
> +    cstring impl::file_file = "logs/legion-engine.log";
`file_file` ?

2020-12-21 21:22 UTC, Algo-ryth-mix commented on legion/engine/core/logging/logging.hpp
> +#else
I am not 100% certain that LOG_FILE is required at all when logging via console

2020-12-21 21:22 UTC, Algo-ryth-mix commented on legion/engine/core/logging/logging.hpp
> +#else
this is very likely to cause problems when events are logged before the engine is started up. I would recommend settting the default logger to be the console logger at first and replacing it with the file logger if necessary

2020-12-22 20:12 UTC, GlynLeine commented
@Algo-ryth-mix I applied your requested changes!

2020-12-22 21:20 UTC, Algo-ryth-mix approved these changes

2020-12-22 21:20 UTC, Algo-ryth-mix approved these changes

2020-12-22 21:44 UTC, merged