Middle phase collision
Args-Engine/Args-Engine pull request #301
Opened 2021-01-26 14:43 UTC by Jelled1st

Adds a layer of collision checking between broad-phase and narrow-phase collision. This middle-phase does AABB collision between colliders before going into the actual narrow-phase.

2021-01-26 14:47 UTC, Developer-The-Great approved these changes

2021-01-26 16:48 UTC, GlynLeine commented
It's crashing for me after the merge, needs some attention tomorrow

2021-01-26 16:48 UTC, GlynLeine requested changes
It's crashing for me after the merge, needs some attention tomorrow

2021-01-27 13:54 UTC, GlynLeine approved these changes

2021-01-27 14:05 UTC, merged